version: '3.6'

services:
  mainnet:
    image: kylemanna/bitcoind
    restart: always
    user: root
    command: bitcoind
    ports:
      - "8332:8332"
    volumes:
      - ./keys/mainnet:/bitcoin/wallet
      - ./blocks/mainnet:/bitcoin/.bitcoin/blocks
      - ./config/mainnet-bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf

  testnet:
    image: kylemanna/bitcoind
    restart: always
    user: root
    command: bitcoind
    ports:
      - "18332:18332"
    volumes:
      - ./keys/testnet:/bitcoin/wallet
      - ./blocks/testnet:/bitcoin/.bitcoin/testnet3/blocks
      - ./config/testnet-bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
